# Generated by Django 5.2.14 on 2026-05-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Plate Number"
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Unit Number"
                    ),
                ),
                (
                    "truck_type",
                    models.CharField(
                        choices=[
                            ("flatbed", "Flatbed"),
                            ("box", "Box Truck"),
                            ("refrigerated", "Refrigerated"),
                            ("tanker", "Tanker"),
                            ("dump", "Dump Truck"),
                            ("container", "Container"),
                            ("other", "Other"),
                        ],
                        default="flatbed",
                        max_length=30,
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Capacity in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("year_model", models.IntegerField(blank=True, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("registration_expiry", models.DateField(blank=True, null=True)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("on_trip", "On Trip"),
                            ("maintenance", "Under Maintenance"),
                            ("inactive", "Inactive"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
