# Generated by Django 5.2.14 on 2026-05-29 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_receipt"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="maintenance_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expense_record",
                to="maintenance.maintenance",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("fuel", "Fuel"),
                    ("toll", "Toll"),
                    ("repair", "Repair"),
                    ("maintenance", "Maintenance"),
                    ("allowance", "Driver Allowance"),
                    ("parking", "Parking"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
