# Generated by Django 5.2.14 on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture_data",
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture_mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
