# Generated by Django 5.2.14 on 2026-05-27 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="delivery_proof",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="delivery_proofs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf", "doc", "docx"]
                    )
                ],
            ),
        ),
    ]
